### ISSUE TITLE
Does not install anymore

### ISSUE THREAD

**Issue by raffaelemancuso** [Perlence/dropbox-via-webdav#3]
It looks like WsgiDAV==1.1.0 only works with python 2, and requires `python` to be set to `python2`

```
$ pip install -r requirements.txt 
Collecting arrow==0.5.0
  Using cached arrow-0.5.0.tar.gz (78 kB)
Collecting dropbox==2.2.0
  Using cached dropbox-2.2.0.zip (691 kB)
Collecting python-dateutil==2.4.0
  Using cached python_dateutil-2.4.0-py2.py3-none-any.whl (175 kB)
Collecting six==1.9.0
  Using cached six-1.9.0-py2.py3-none-any.whl (10 kB)
Collecting urllib3==1.10
  Using cached urllib3-1.10.tar.gz (128 kB)
Collecting WsgiDAV==1.1.0
  Using cached WsgiDAV-1.1.0.zip (206 kB)
    ERROR: Command errored out with exit status 1:
     command: /media/raffaele/DATA/progetti_altrui/dropbox-via-webdav/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_wpz7_f2/wsgidav_572874a89dc74fd881e0989c20f3d121/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_wpz7_f2/wsgidav_572874a89dc74fd881e0989c20f3d121/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-yw8aleq1
         cwd: /tmp/pip-install-_wpz7_f2/wsgidav_572874a89dc74fd881e0989c20f3d121/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_wpz7_f2/wsgidav_572874a89dc74fd881e0989c20f3d121/setup.py", line 17
        print "Initializing HOME environment variable to '%s'" % os.environ["HOME"]
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Initializing HOME environment variable to '%s'" % os.environ["HOME"])?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.3.3; however, version 21.0.1 is available.
You should consider upgrading via the '/media/raffaele/DATA/progetti_altrui/dropbox-via-webdav/env/bin/python -m pip install --upgrade pip' command.
```

**Comment by Perlence** [comment]
Hello @raffaem! I haven't used Dropbox in 6 years, so I guess problems like this are bound to happen.

I'm sorry, but I'm going to archive this repo. Feel free to use this code in your own projects!
